development:
  adapter: postgresql
  encoding: unicode
  database: rails_tut_dev
  pool: 5
  host: localhost
  port: 5432  
   

test:
  adapter: postgresql
  encoding: unicode
  database: rails_tut_test
  pool: 5
  host: localhost
  port: 5432  
